### ISSUE TITLE
Read '2' instead of '-' in pdfs

### ISSUE THREAD

**Issue by ammirsm** [jalan/pdftotext#25]
I'm using your library for reading some PDFs, some of the issues are happens in reading them.

I am reading this pdf and it read '2' instead of '-'.

The sample pdf is in this link
https://docdro.id/twWPwGC

Thanks

**Comment by jalan** [comment]
That's not an issue with this library. It looks like an issue with how fonts are used in the PDF. My guess is that instead of encoding "–" as "–", this PDF has encoded "–" as "2" and used a custom font encoding to make it display as "–". This sort of nonsense is unfortunately common in the PDF world.

Indeed, you can see in Adobe Reader that this PDF has custom font encodings:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/305841/48782647-df957480-ec9b-11e8-8772-5e8604972422.png">
