### ISSUE TITLE
Aborted (core dumped) 

### ISSUE THREAD

**Issue by valterartur** [jalan/pdftotext#64]
Hi there, your software is really good and I'm using it to extract text from some pdfs but unfortunately i  I encountered an error that appears when I try text from probably harmed pdfs (they don't open on my computer).
Reproduce issue:
```
import requests
import pdftotext

r = requests.get("https://ttd.gov/wp-content/uploads/2019/03/3-4-19-Commission-Packet.pdf")
open("crash.pdf", "wb").write(r.content)
with open("crash.pdf", "rb") as f:
	text = pdftotext.PDF(f)
	print(list(text))
```
output: `Aborted (core dumped)`

And my script is falling down without an opportunity to handle it with exception.
May be there is another way to handle this error? for my script got next file to extract

**Comment by jalan** [comment]
The code you posted works fine for me, using poppler 0.88. What version of poppler do you have? An up to date version is less likely to exhibit crashes.

Since this python library uses a C library, if a fatal error happens in the C code, there is usually no way to catch that error in python. One possibility is to use the [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) module to perform your text extraction in a separate process, and then you can catch if that process crashes.

The code [here](https://github.com/jalan/pdftotext/issues/46#issuecomment-559644261) should give you a starting point.
