### ISSUE TITLE
This project should be released with GPL license

### ISSUE THREAD

**Issue by elonzh** [jalan/pdftotext#81]
see https://gitlab.freedesktop.org/poppler/poppler#history-and-gpl-licensing

```
Please note that xpdf, and thus poppler, is licensed under the GPL, not the LGPL. Consequently, any application using poppler must also be licensed under the GPL.
```

**Comment by jalan** [comment]
Do you represent the poppler project in this matter?

**Comment by elonzh** [comment]
No, just a friendly reminder.

**Comment by exikyut** [comment]
Currently looking for a way to do text extraction for a small personal project I don't want to dump on the internet. Naturally came across Poppler pretty quickly, and because the license position is called out very clearly on the homepage I was able to immediately know I needed to move on.

The current top results for "pdftotext" find this python library very quickly. My understanding of the GPL is that it is viral, **meaning that anything using Poppler, including this library, *and all software that depends on this library*, must also be GPL.**

This project currently has 17 watchers and 495 stars. It would be a great service to relicense this ASAP so downstream users do not get bitten.

Now to go find an alternative library that's as easy to use :'(...

**Comment by jalan** [comment]
> My understanding of the GPL is that it is viral, meaning that anything using Poppler, including this library, and all software that depends on this library, must also be GPL.

Maybe that's the _intent_ of the GPL, sure? But is this project a derivative work merely because it can link to a completely unmodified poppler library? That issue is for courts to decide, and after 30-some years, they still haven't, unless I missed something.

If you want to distribute a program that uses this library and poppler, and you are concerned about licensing, you should seek legal counsel.
